version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "22:15"
      timezone: Asia/Shanghai
    groups:
      npm:
        patterns:
          - "*"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "22:15"
      timezone: Asia/Shanghai
    groups:
      gha:
        patterns:
          - "*"
